### ISSUE TITLE
TypeError: Cannot read property 'isServer' of undefined

### ISSUE THREAD

**Issue by sergeu90** [AlexBeauchemin/webpack-delete-sourcemaps-plugin#5]
When i use 

` new DeleteSourceMapsPlugin(),`

then i have error in output 

TypeError: Cannot read property 'isServer' of undefined

webpack 5.

TypeError: Cannot read property 'isServer' of undefined I think issue here https://github.com/AlexBeauchemin/webpack-delete-sourcemaps-plugin/blob/main/index.ts#L8  to need 

```
constructor({ isServer = null } = {}) {
    this.isServer = isServer
  }
```

**Comment by AlexBeauchemin** [comment]
Good catch, fixed it in v1.1.1
https://github.com/AlexBeauchemin/webpack-delete-sourcemaps-plugin/pull/6
