### ISSUE TITLE
Webpack 4 support 

### ISSUE THREAD

**Issue by probil** [AlexBeauchemin/webpack-delete-sourcemaps-plugin#9]
Hi Alex,
We've just deployed your plugin to our server and it seems to be working fine with webpack 4. 

We use Vue CLI with `webpack@4.46.0` under the hood.

Could you please adjust README so others can try that as well, and update your `package.json` so we don't have to download entire `webpack@5` when we don't need it?

E.g.:
```diff
  "optionalDependencies": {
-    "webpack": "^5.63.0"
+    "webpack": "4.x || 5.x"   
  }
```

Thanks!

**Comment by AlexBeauchemin** [comment]
Fixed via https://github.com/AlexBeauchemin/webpack-delete-sourcemaps-plugin/pull/10
Release :

**Comment by AlexBeauchemin** [comment]
Thanks for flagging this

Fixed via https://github.com/AlexBeauchemin/webpack-delete-sourcemaps-plugin/pull/10
Release : https://github.com/AlexBeauchemin/webpack-delete-sourcemaps-plugin/releases/tag/v1.3.0

It should work now if you point to v1.3.0
Please reopen if it doesn't fix your issue
